name: bench
on:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run benchmarks
    runs-on: bench
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: openjdk@1.17.0
 
      - name: run benchmarks
        run: |
          cd /home/runner/work/kyo/kyo/
          sbt kyo-bench/"jmh:clean"
          sbt kyo-bench/"jmh:run -wi 10 -i 5 -r 1 -w 1 -t 1 -rf json -foe true -prof gc Kyo" 

      - name: prepare results
        run: |
          mkdir -p output/
          cp -r kyo-bench/.jvm/*.json output/

      - name: publish results
        uses: actions/upload-artifact@v3
        with:
          name: bench
          path: output/**