name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v11
    - name: gen kyo-core-optN
      run: ./opt-gen.sh
    - name: test
      run: sbt test
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # - name: Publish
    #   run: sbt publish
    #   env: 
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
