name: profile
on:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Profile benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: openjdk@1.17.0

      - name: install async-profiler
        run: |
          cd /home/runner
          wget https://github.com/jvm-profiling-tools/async-profiler/releases/download/v2.9/async-profiler-2.9-linux-x64.tar.gz
          tar -xvzf async-profiler-2.9-linux-x64.tar.gz
          sudo mkdir -p /usr/java/packages/lib/
          sudo cp async-profiler-2.9-linux-x64/build/libasyncProfiler.so /usr/java/packages/lib/
          sudo sysctl kernel.perf_event_paranoid=1
          sudo sysctl kernel.kptr_restrict=0

      - name: cpu profiling
        run: |
          cd /home/runner/work/kyo/kyo/
          sbt kyo-bench/"jmh:clean"
          sbt kyo-bench/"jmh:run -wi 1 -i 1 -r 1 -w 1 -t 1 -rf json -foe true -prof async:output=flamegraph Kyo" 

      - name: alloc profiling
        run: |
          cd /home/runner/work/kyo/kyo/
          sbt kyo-bench/"jmh:clean"
          sbt kyo-bench/"jmh:run -wi 1 -i 1 -r 1 -w 1 -t 1 -rf json -foe true -prof \"async:alloc;output=flamegraph\" Kyo"

      - name: Store flamegraphs
        run: |
          git config pull.rebase true 
          export REV=$(git rev-parse --short HEAD)
          mv kyo-bench/kyo.bench.* /tmp
          git clean -fdx
          git checkout gh-pages
          git pull
          mkdir -p dev/profile/$REV
          mv /tmp/kyo.bench.* dev/profile/$REV
          rm -rf dev/profile/**/*reverse*
          cd dev/profile
          find . -maxdepth 1 -type d \( ! -name . \) -exec bash -c "cd '{}' && tree -H . -o index.html" \;
          cd ../../
          git config --global user.name "Kyo CI"
          git config --global user.email "kyoci@users.noreply.github.com"
          git add .
          git commit -m "flamegraphs for $REV"
          git push