name: profile-cpu
on:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Profile benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: openjdk@1.17.0

      - name: install async-profiler
        run: |
          cd /home/runner
          wget https://github.com/jvm-profiling-tools/async-profiler/releases/download/v2.9/async-profiler-2.9-linux-x64.tar.gz
          tar -xvzf async-profiler-2.9-linux-x64.tar.gz
          sudo mkdir -p /usr/java/packages/lib/
          sudo cp async-profiler-2.9-linux-x64/build/libasyncProfiler.so /usr/java/packages/lib/
          sudo sysctl kernel.perf_event_paranoid=1
          sudo sysctl kernel.kptr_restrict=0

      - name: cpu profiling
        run: |
          cd /home/runner/work/kyo/kyo/
          sbt kyo-bench/"jmh:clean"
          sbt kyo-bench/"jmh:run -wi 5 -i 5 -r 1 -w 1 -t 1 -rf json -foe true -prof async:output=flamegraph" 

      - name: prepare results
        run: |
          mkdir -p output/
          cp -r kyo-bench/kyo.bench.* output/
          rm -rf output/**/*reverse.html

      - name: publish results
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'output'
          target-directory: 'dev/profile/${{ github.sha }}/cpu/'
          destination-github-username: 'getkyo'
          destination-repository-name: 'website'
          user-email: getkyo.io@gmail.com
          target-branch: main