name: readme
on: [push, pull_request]
jobs:
  readme:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: adopt@1.11
      - run: sbt checkReadme
